import type { ProductThemeDefinition } from '../types';
import { azureBrand } from '../azureThemes';

/**
 * Azure product overrides are color-only. Structural tokens (borderRadius, spacing, shadows)
 * come from the design-system skin layer.
 */
const azureColorOverrides = {
  colorNeutralBackground1: '#ffffff',
  colorNeutralBackground2: '#fafafa',
  colorNeutralBackground3: '#f5f5f5',
  colorNeutralBackground4: '#f0f0f0',
  colorNeutralBackground5: '#ebebeb',
  colorNeutralBackground6: '#e6e6e6',
  colorNeutralForeground1: '#242424',
  colorNeutralForeground2: '#424242',
  colorNeutralForeground3: '#616161',
  colorNeutralForeground4: '#707070',
  colorNeutralForegroundDisabled: '#bdbdbd',
  colorNeutralStroke1: '#d1d1d1',
  colorNeutralStroke2: '#e0e0e0',
  colorNeutralStroke3: '#f0f0f0',
  colorNeutralStrokeAccessible: '#616161',
  colorNeutralStrokeDisabled: '#e0e0e0',
  colorPaletteRedForeground1: '#bc2f32',
  colorPaletteRedBackground1: '#fdf3f4',
  colorPaletteRedBackground2: '#eeacb2',
  colorPaletteRedBackground3: '#c50f1f',
  colorPaletteRedBorder1: '#eeacb2',
  colorPaletteGreenForeground1: '#0e700e',
  colorPaletteGreenBackground1: '#f1faf1',
  colorPaletteGreenBackground2: '#9fd89f',
  colorPaletteGreenBackground3: '#107c10',
  colorStatusDangerBackground1: '#f6d1d5',
  colorStatusDangerBackground2: '#eeacb2',
  colorStatusDangerBackground3: '#c50f1f',
  colorStatusDangerForeground1: '#b10e1c',
  colorStatusDangerForeground3: '#c50f1f',
  colorStatusDangerBorder1: '#eeacb2',
  colorStatusDangerBorder2: '#c50f1f',
  colorStatusSuccessBackground1: '#c9eac9',
  colorStatusSuccessBackground2: '#9fd89f',
  colorStatusSuccessBackground3: '#107c10',
  colorStatusSuccessForeground1: '#0e700e',
  colorStatusSuccessForeground3: '#107c10',
  colorStatusSuccessBorder1: '#9fd89f',
  colorStatusSuccessBorder2: '#107c10',
  colorStatusWarningBackground1: '#fee5d7',
  colorStatusWarningBackground2: '#fdcfb4',
  colorStatusWarningBackground3: '#f7630c',
  colorStatusWarningForeground1: '#bc4b09',
  colorStatusWarningForeground3: '#bc4b09',
  colorStatusWarningBorder1: '#fdcfb4',
  colorStatusWarningBorder2: '#bc4b09',
  colorStrokeFocus1: '#ffffff',
  colorStrokeFocus2: '#000000',
};

export const azureProductTheme: ProductThemeDefinition = {
  id: 'azure',
  displayName: 'Azure',
  description: 'Default Azure Portal theme — Coherence design system tokens',
  brand: azureBrand,
  lightOverrides: azureColorOverrides,
  darkOverrides: {
    colorBrandForeground1: azureBrand[110],
    colorBrandForeground2: azureBrand[120],
  },
  highContrastOverrides: undefined,
};
